version: "3.9"
# NET
networks:
  proxy-redirect:
    external: false
    name: proxy-redirect

services:
  zookeeperDest:
    image: confluentinc/cp-zookeeper
    container_name: zdest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/zookeeper_jaas.conf
    networks:
      - proxy-redirect
    volumes:
      - ./Zoo-dest/secrets:/etc/zookeeper
  
  destbro:
    image: confluentinc/cp-kafka
    container_name: kdest
    depends_on:
      - zookeeperDest
    networks:
      - proxy-redirect
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeperDest:2182
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # DEV
      KAFKA_LISTENERS: SSL://:9093, kdest://:9094, localhost://:9092
      KAFKA_ADVERTISED_LISTENERS: SSL://10.0.7.115:29093,kdest://10.0.7.115:29094, localhost://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: kdest:SASL_SSL,SSL:SSL,localhost:PLAINTEXT
      # PROD
      # KAFKA_ADVERTISED_LISTENERS: SSL://:9093,kdest://:9094
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: kdest:SASL_SSL, SSL:SSL
      
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks      
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks

      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore-cred
      KAFKA_SSL_KEY_CREDENTIALS: keystore-cred
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: keystore-cred
      
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISMS_INTER_BROKER_PROTOCOL: PLAIN
    
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_dest_jaas.conf
    volumes:
      - ./Kafka-dest/secrets/:/etc/kafka/secrets
    ports:
      - 29093:9093
      - 29094:9094
                  