version: "3.9"
# NET
networks:
  kafka-net:
    name: kafka-net

services:
# ZOOKEEPER
  zookeeperSource:
    image: confluentinc/cp-zookeeper
    container_name: zsource
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  zookeeperDest:
    image: confluentinc/cp-zookeeper
    container_name: zdest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
    networks:
      - kafka-net

# KAFKA 
  sourcebro:
    container_name: ksource
    depends_on:
      - zookeeperSource
    build:
      context: .
      dockerfile: ./Kafka-source/Dockerfile-source
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeperSource:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ksource:9092
    networks:
      - kafka-net
    #command: sh -c "./home/appuser/topicCreation.sh"
  
  destbro:    
    container_name: kdest
    depends_on:
      - zookeeperDest
    build:
      context: .
      dockerfile: ./Kafka-dest/Dockerfile-dest
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeperDest:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://destbro:9093
    networks:
      - kafka-net


# REPLICATOR
  # mirror-maker:
  # container_name: replicator
  # depends_on:
  #   - sourcebro
  #   - destbro
  # build:
  #     context: .
  #     dockerfile: ./MMaker/Dockerfile-mm