version: "3.9"
# NET
networks:
  kafka-net:
    name: kafka-net

services:
# UTILS Containers
  # minibox:
  #   image: busybox
  #   container_name: utils
  #   command: tail -F anything # wait undefinetly the file "anything"
  #   networks:
  #     - kafka-net
    
# ZOOKEEPER
  zookeeperSource:
    image: confluentinc/cp-zookeeper
    container_name: zsource
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  zookeeperDest:
    image: confluentinc/cp-zookeeper
    container_name: zdest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2182
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/zookeeper/zookeeper_jaas.conf
    networks:
      - kafka-net
    volumes:
      - ./Zoo-dest/secrets:/etc/zookeeper

# KAFKA 
  sourcebro:
    container_name: ksource
    depends_on:
      - zookeeperSource
    build:
      context: .
      dockerfile: ./Kafka-source/Dockerfile-source
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeperSource:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ksource:9092      
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - kafka-net
  
  destbro:
    container_name: kdest
    depends_on:
      - zookeeperDest
    build:
      context: .
      dockerfile: ./Kafka-dest/Dockerfile-dest
    networks:
      - kafka-net
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeperDest:2182
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # DEV
      KAFKA_ADVERTISED_LISTENERS: SSL://:9093,kdest://:9094, localhost://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: kdest:SASL_SSL, SSL:SSL, localhost:PLAINTEXT
      # PROD
      # KAFKA_ADVERTISED_LISTENERS: SSL://:9093,kdest://:9094
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: kdest:SASL_SSL, SSL:SSL
      
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks      
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks

      KAFKA_SSL_KEYSTORE_CREDENTIALS: keystore-cred
      KAFKA_SSL_KEY_CREDENTIALS: keystore-cred
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: keystore-cred
      
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL

      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISMS_INTER_BROKER_PROTOCOL: PLAIN
    
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_dest_jaas.conf
    volumes:
      - ./Kafka-dest/secrets/:/etc/kafka/secrets
    ports:
      - 29093:9093
      - 29094:9094

# MIRROR
  mirror-maker:
    container_name: replicator
    depends_on:
      # - kafka-setup
      - destbro
      - sourcebro
    build:
      context: .
      dockerfile: ./LMM/Dockerfile-lmm
    networks:
      - kafka-net
    volumes:
      - ./LMM/secrets/:/etc/kafka/secrets
            