FROM debian

ENV MYHOME="/root"
ENV WORKDIR="$MYHOME/workspace"
ENV KAFKA_MIRROR="https://dlcdn.apache.org/kafka/3.1.0/kafka_2.13-3.1.0.tgz"
ENV KAFKA_HOME="$WORKDIR/kafka_2.13-3.1.0"

# Installing dependencies (and Java 11)
RUN apt update && \
    apt install -y sudo git iputils-ping curl apt-transport-https ca-certificates wget dirmngr gnupg software-properties-common vim default-jdk

# Download Kafka
RUN mkdir -p $WORKDIR && \
    cd $WORKDIR && \
    wget -c $KAFKA_MIRROR -O - | tar -xz

COPY ./LMM/mmaker.properties $KAFKA_HOME/bin/mmaker.properties

# Make Kafka binaries executable
ENV PATH="$KAFKA_HOME/bin:${PATH}"

# Run the mirror
ENTRYPOINT connect-mirror-maker.sh $KAFKA_HOME/bin/mmaker.properties
