FROM alpine

ENV MYHOME="/root"
ENV WORKDIR="$MYHOME/workspace"
ENV KAFKA_MIRROR="https://dlcdn.apache.org/kafka/3.1.0/kafka_2.13-3.1.0.tgz"
ENV KAFKA_HOME="$WORKDIR/kafka_2.13-3.1.0"

# Installing dependencies (and Java 11)
RUN apk --update-cache upgrade && \
    apk add openjdk11 wget && \
    apk add --no-cache --upgrade bash

# Download Kafka
RUN mkdir -p $WORKDIR && \
    cd $WORKDIR && \
    wget -c $KAFKA_MIRROR -O - | tar -xz

# Make Kafka binaries executable
ENV PATH="$KAFKA_HOME/bin:${PATH}"

# only debug
# COPY secrets/mmaker.properties /etc/kafka/secrets/mmaker.properties
# RUN ls -lha $KAFKA_HOME/bin/connect-mirror-maker.sh
# RUN cat /etc/kafka/secrets/mmaker.properties

# Run the mirror
ENTRYPOINT $KAFKA_HOME/bin/connect-mirror-maker.sh /etc/kafka/secrets/mmaker.properties